/**
 * Build src/lib/notalm/corpus.generated.ts from corpus/claims/*.yml
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import {
  finalizeClaim,
  langsOfClaim,
} from "../src/lib/notalm/corpus-author.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const claimsDir = join(root, "corpus", "claims");
const outPath = join(root, "src", "lib", "notalm", "corpus.generated.ts");

const files = readdirSync(claimsDir)
  .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
  .sort();

if (files.length === 0) {
  console.error(`no claim files in ${claimsDir}`);
  process.exit(1);
}

const claims = [];
for (const file of files) {
  const raw = parse(readFileSync(join(claimsDir, file), "utf8"));
  if (!raw?.claim) {
    console.error(`missing claim in ${file}`);
    process.exit(1);
  }
  const finalized = finalizeClaim(raw);
  if (langsOfClaim(finalized).length === 0) {
    console.error(`${file}: need at least one of ja/en/zh`);
    process.exit(1);
  }
  claims.push(finalized);
}

mkdirSync(dirname(outPath), { recursive: true });
const body = `/* eslint-disable */
/** AUTO-GENERATED by \`npm run corpus:build\` — do not edit. */
import type { AuthorClaim } from "./corpus-author";

export const GENERATED_CLAIMS: AuthorClaim[] = ${JSON.stringify(claims, null, 2)};
`;
writeFileSync(outPath, body, "utf8");
console.log(`built ${claims.length} claims → ${outPath}`);
